### PR TITLE
replace dropdown button from "V" to faCaretDown

### PR DESCRIPTION
**Pull request by charrrleee**
use awesome icon to replace "V"

Screenshot 2023-10-24 at 09 57 59

### CODE REVIEW

**Review by krissolui — APPROVED** [review]
looks great

**Comment by wkip1220withweb** [comment]
Yes. It looks better.

**Review by louvrecly — APPROVED** [review]

**Comment by louvrecly** [comment]
rebased from the latest `main` branch and resolved conflicts

**Comment by wkip1220withweb** [comment]
Screen-default@1x (1)
Great. Please keep going and is it too complicated to merge the layout like this screenshot shown? The style of contents remains unchanged.

**Pull request merged**
